use ptd;
insert into member(email, password) values ('test@abc.co.kr', '15d2d4^$3');
set @member_pk = LAST_INSERT_ID();
insert into plan(member_id, start_date, end_date, status, title) values (@member_pk, '2023-11-01', '2023-11-11', 0, 'plan1');
set @plan_pk = LAST_INSERT_ID();
insert into repetition(rep_option, rep_value) values (3, '1010100');
set @rep1_pk = LAST_INSERT_ID();
insert into repetition(rep_option, rep_value) values (1, '-1');
set @rep2_pk = LAST_INSERT_ID();
insert into repetition(rep_option, rep_value) values (2, '2');
set @rep3_pk = LAST_INSERT_ID();
insert into group_table(plan_id, rep_id, title) values (@plan_pk, @rep1_pk, 'group1');
set @grp1_pk = LAST_INSERT_ID();
insert into group_table(plan_id, rep_id, title) values (@plan_pk, @rep2_pk, 'group2');
set @grp2_pk = LAST_INSERT_ID();
insert into group_table(plan_id, rep_id, title) values (@plan_pk, @rep3_pk, 'group3');
set @grp3_pk = LAST_INSERT_ID();
insert into checkbox(group_id, title, date_key, checked) values (@grp1_pk, 'checkbox1', '2023-11-01', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp1_pk, 'checkbox2', '2023-11-03', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp1_pk, 'checkbox3', '2023-11-06', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp1_pk, 'checkbox4', '2023-11-08', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp1_pk, 'checkbox5', '2023-11-10', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox1', '2023-11-01', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox2', '2023-11-02', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox3', '2023-11-03', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox4', '2023-11-04', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox5', '2023-11-05', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox6', '2023-11-06', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox7', '2023-11-07', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox8', '2023-11-08', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox9', '2023-11-09', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox10', '2023-11-10', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp2_pk, 'checkbox11', '2023-11-11', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp3_pk, 'checkbox1', '2023-11-01', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp3_pk, 'checkbox2', '2023-11-03', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp3_pk, 'checkbox3', '2023-11-05', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp3_pk, 'checkbox4', '2023-11-07', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp3_pk, 'checkbox5', '2023-11-09', 0);
insert into checkbox(group_id, title, date_key, checked) values (@grp3_pk, 'checkbox6', '2023-11-11', 0);