version: '3.8'
services:
  db:
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    command:
      - --lower_case_table_names=1
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ptd
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  spring:
    image: yeonleaf/ptd:latest
    ports:
      - '8080:8080'
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

volumes:
  db-data:
