name: CD using Github Actions and Docker

on:
  push:
    branches:
      - 'main'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -  
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }}
      -
        name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # - 
      #   name: Validate Gradle wrapper
      #   uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      # - 
      #   name: Setup MySQL
      #   uses: samin/mysql-action@v1.3
      #   with:
      #     host port: 3306
      #     container port: 3306
      #     mysql version: '8.0'
      #     mysql database: 'ptd'
      #     mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      #     mysql user: 'admin'
      #     mysql password: ${{ secrets.MYSQL_PASSWORD }}
      # -
      #   name: Grant execute permission for gradlew
      #   run: chmod +x gradlew
      #   working-directory: plantodo
      - 
        name: Build with Gradle
        run: gradle --debug build
        working-directory: plantodo
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ptd:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACTION_TOKEN }}
      # -
      #   name: EC2 Docker run
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_KEY }}
      #     script: |
      #       docker rm -f $(docker ps -qa)
      #       docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/ptd:latest
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ptd:latest
      #       docker-compose up -d
