name: CD using Github Actions and Docker

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout submodules
      uses: actions/checkout@v4
      with:
        repository: yeonleaf/plantodo-private
        token: ${{ secrets.ACTION_TOKEN }}
        path: submodule
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ptd:latest
    - name: EC2 Docker run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker rm -f $(docker ps -qa)
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/ptd:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ptd:latest
          docker-compose up -d
      
