name: test removing flyway and docker-compose (docker image build)

on:
  push:
    branches:
      - 'delflyway'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -  
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }}
      -
        name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      -
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: plantodo
      - 
        name: Build with Gradle
        run: gradle clean build
        working-directory: plantodo
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker image
        run: |
          docker build -t ptd .
          docker tag ptd yeonleaf/ptd:dev-test
          docker push yeonleaf/ptd:dev-test
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 487437989384.dkr.ecr.ap-northeast-2.amazonaws.com
          docker tag yeonleaf/ptd:dev-test 487437989384.dkr.ecr.ap-northeast-2.amazonaws.com/ptd:dev
          docker push 487437989384.dkr.ecr.ap-northeast-2.amazonaws.com/ptd:dev
